#!/usr/bin/perl
use strict;
use File::Basename;
use Cwd 'abs_path';

#################################################################
# Disclaimer: DeepFold is the software developed at Y Zhang Lab #
# at CCMB, University of Michigan. No any part of this package  #
# could be released outside the Zhang Lab without permission    #
# from the orginal authors. Violation of this rule may result   #
# in lawful consequences.                                       #
#################################################################

############################################################
# This script will generate contact prediction from
# different programs for C-QUARK.
#     input:
#       seq.txt (query sequence in FASTA format)
#       phi.txt (predicted phi angles)
#       psi.txt (predicted psi angles)
#       seq.data.ss (predicted secondary structure)
#       DeepPotential_20.npz.gz  (DeepPotential Distance/Orientation restraints)
#       DeepPotential_pca_20.txt (DeepPotential CA distances)
#       DeepPotential_ca_contact.txt.gz (DeepPotential CA contacts)
#       DeepPotential_cb_contact.txt.gz (DeepPotential CB contacts)
#     output:
#       full_atom_model.pdb    (full atom model generated by DeepFold) 
############################################################


######### variables may need to change #####################
my @ss;
my $outdir;
my $refine_flag;
my $distancedir=dirname(abs_path(__FILE__))."/../distance/"; #where distance predictors are
#####################################################

#### command line arguments can overwrite the above variables ####
if (@ARGV>0)
{
    my $datadir=abs_path($ARGV[0]);
    $outdir=dirname($datadir);
    @ss=(basename($datadir));
    if (! -d "$datadir") # target list 
    {
        @ss=();
        foreach my $s(`grep -ohP '^\\S+' $datadir`)
        {
            chomp($s);
            push @ss, $s;
        }
    }
    $refine_flag="$ARGV[1]";
}
$outdir=abs_path($outdir);

#################################################################
my @DF=qw(
    DeepFold
);

foreach my $s(@ss)
{
    my $datadir="$outdir/$s";

    if(!-s "$datadir/MSA/protein.aln")
    {
        print "Error! $datadir/MSA/protein.aln missing. Skip $s\n";
        next;
    }
    print "$datadir/MSA/protein.aln is available. Let's predict spatial restraints.\n";

    my $recorddir="$datadir/record"; #all log files and intermediate job files
    system("mkdir -p $recorddir");

    my $sequence=`head -1 $datadir/MSA/protein.aln`;
    chomp($sequence);
    my $Lch=length $sequence;

    foreach my $F(@DF)
    {
        my $tag="DeepFold\_$s"; # unique name
        if(-s "$datadir/full_atom_model.pdb")
        {
            print "Model is generated. Let's skip\n";
            next;
        }
        my $walltime="24:00:00";
        my $mem="8000mb";
        if ($Lch>300)
        {
            $walltime="48:00:00";
            $mem="12000mb";
        }
        my $jobname="$recorddir/$tag";
        open(FP,">$jobname");
        print FP<<EOF
#!/bin/bash
#SBATCH -e $jobname.err
#SBATCH -o $jobname.out
#SBATCH -t $walltime
#SBATCH --mem=$mem
#SBATCH --job-name=$tag

echo hostname: `hostname`
echo starting time: `date`
echo pwd `pwd`

$distancedir/${F}mod.pl $datadir $tag $refine_flag

echo ending time: `date`
EOF
;
        close(FP);
        system("chmod a+x $jobname");
        system("$jobname");

        #### record submission status ####
=pod
        my $bsub='';
        while(length $bsub ==0)
        {
            $bsub=`sbatch $jobname`;
            chomp($bsub);
            last if (length $bsub);
            sleep(20);
        }
        my $date=`date`;
        chomp($date);
        open(FP,">>$recorddir/note.txt");
        print "$jobname\t at $date $bsub\n";
        print FP "$jobname\t at $date $bsub\n";
        close(FP);
=cut
    }
}
exit();
