# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap;/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Stefan Seemayer")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_GENERATOR "DEB;RPM")
set(CPACK_INSTALL_CMAKE_PROJECTS "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap;CCMpred;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/cmake_lib/")
set(CPACK_NSIS_DISPLAY_NAME "ccmpred 0.3.3")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "ccmpred 0.3.3")
set(CPACK_OUTPUT_CONFIG_FILE "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Protein residue-residue contacts from correlated mutations predicted accurately and quickly")
set(CPACK_PACKAGE_EXECUTABLES "CCMpred;CCMpred")
set(CPACK_PACKAGE_FILE_NAME "CCMpred-0.3.3-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "ccmpred 0.3.3")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ccmpred 0.3.3")
set(CPACK_PACKAGE_NAME "CCMpred")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_RESOURCE_FILE_LICENSE "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/LICENSE")
set(CPACK_PACKAGE_VENDOR "AG Soeding")
set(CPACK_PACKAGE_VERSION "0.3.3")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "3")
set(CPACK_RESOURCE_FILE_LICENSE "/sw/arcts/centos7/cmake/3.13.2/share/cmake-3.13/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/sw/arcts/centos7/cmake/3.13.2/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/sw/arcts/centos7/cmake/3.13.2/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_GROUP "Application/Engineering")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3+")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "_CPack_Packages;.git;.mat;bin;CMakeFiles;.zip;.tar.gz;.rpm;.deb;.swp;CMakeCache.txt;CPackSourceConfig.cmake;CPackConfig.cmake;cmake_install.cmake;install_manifest.txt;.pyc")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "ccmpred-0.3.3")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_STRIP_FILES "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "bin/ccmpred")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/nfs/amino-home/zcx/Projects/QUARK/version_2020_05_05/distance/ResTriplet3_04132020/ccmpred_gap/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
